import LayoutWrapper from "@/components/LayoutWrapper/LayoutWrapper";
import  "bootstrap/dist/css/bootstrap.min.css"
import "bootstrap/dist/css/bootstrap.css";
import '@mdi/font/css/materialdesignicons.min.css';
import "flag-icon-css/css/flag-icons.min.css";
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { CountryProvider } from "@/contexts/CountryContext";
import { UserProvider } from "@/contexts/UserContext";
import "./globals.css";




export const metadata = {
  title: "Ohana Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer/>
        <CountryProvider>
          <UserProvider>
            <LayoutWrapper>
              {children}
            </LayoutWrapper>
          </UserProvider>
        </CountryProvider>
      </body>
    </html>
  );
}
