import { useState } from "react";
export function PrivacyPolicy() {
    const [ isFrench, setIsFrench ] = useState(false);
    return (
        <>
            <div>
                <div className="d-flex align-items-center auth px-0 mt-5">
                    <div className="row w-100 mx-0">
                        <div className="col-lg-6 mx-auto">
                            <div className="auth-form-light text-left py-5 px-4 px-sm-5 my-5 shadow-lg">
                            { isFrench ?
                                    <span onClick={ () => setIsFrench(false) } style={{ float: 'right', cursor: 'pointer' }}><u>English</u></span>
                                    : <span onClick={ () => setIsFrench(true) } style={{ float: 'right', cursor: 'pointer' }}><u>French</u></span>
                                }
                                <div hidden={isFrench == true}>
                                    <h2 className="font-weight-bold text-black">Privacy Policy.</h2>
                                    <h4 className="font-weight-bold text-black">General</h4>
                                    <p>
                                        Ohana Africa (“Ohana Africa”, “we”, “our” or “us”) recognizes the importance of protecting personal details and information, and thus provides this Privacy Policy with respect to the access and use of various products and services of Ohana Africa  by way of any type of devices and media, including web-based, mobile-based applications, devices, URLs/links, notifications, chatbot  and other forms of digital or non-digital media, (“Platforms”) as owned and operated by us and/or our affiliates and services provided thereon by us and/or our affiliates (“Services”). The term Platforms will also include all pages that are sub-domains or are associated with or within each Platform and all devices, applications, features, technologies, functionalities and other services that Ohana Africa operates or offers through such Platforms.

                                        For the purpose of this Privacy Policy, the user of Services may be customers, channel partners, vendors or any other persons using Services or accessing the Platforms (“user”, “you” or “your”). This Privacy Policy will help you understand our policies and procedures regarding the collection, handling and use of your information.
                                        We are committed to respecting your online privacy and recognize your need for appropriate protection and management of any information you share with us on the Platform.

                                        This Privacy Policy (“Policy”) is being framed in accordance under the applicable law.
                                        By using our Services through the Platforms, you signify your assent to this Policy and consent to the processing of your personal information and/or sensitive personal data or any other transaction that is generated with your use of the Platforms (“Information”). If at any time, an individual provides Information about someone other than himself or herself, the individual warrants that they have that person’s consent to provide such information for the purpose specified. The Services are not available to persons below the age of 18 years.
                                        If you do not agree with this Policy, ensure that you do not, in any manner, use our Services or download, install and/or use the mobile application.

                                    </p>
                                    <h4 className="font-weight-bold text-black">SCOPE</h4>
                                    <p>By accessing or using the Platform and/or availing the services provided through the Platform or otherwise giving us your information, you undertake that you have the capacity to enter into a legally binding contract vide this Policy, which constitutes a legally binding document between you and Ohana Africa under the applicable law. Ohana Africa collects and processes your usage data, personal data and third-party data carefully, only for the purposes described in this Policy and only to the extent necessary as defined herein and within the scope of all applicable legal regulations. This Policy seeks to ensure that any personal information or third-party information handled by Ohana Africa is managed in a way that is ethical, compliant and adheres to the best industry practices.

                                        This Policy describes the types of information Ohana Africa collects, why and how Ohana Africa uses the information, with whom Ohana Africa shares it, and the choices you can make about Ohana Africa use of the information. We also describe the measures taken by us to protect the security of the Information and how you can contact Ohana Africa about its privacy practices.

                                        This Policy describes Ohana Africa current data protection policies and practices which may be amended or updated from time to time. Any changes to this Policy will become effective upon posting of the revised Policy on the Platform. It is recommended that you regularly check this Policy to apprise yourself of any updates. Your continued use of Platform or provision of data or information thereafter will imply your unconditional acceptance of such updates to this Policy.
                                    </p>
                                    <h4 className="font-weight-bold text-black">COLLECTION OF INFORMATION</h4>
                                    <p>We intend to provide services and features that meet your needs. To do so, when You use our Platforms, we may obtain the following information about you and your device from which you avail Services</p>
                                    <h4 className="font-weight-bold text-black">THE TYPES OF INFORMATION WE COLLECT IN THE APP</h4>
                                    <p></p>
                                    <h4 className="font-weight-bold text-black"></h4>
                                    <p>Through your use of the Services, we may collect personal information from you in the following ways:</p>
                                    <strong>(a)</strong> Personal Information You Provide to Us
                                    <li>We may collect personal information from you, such as your first and last name, address, email, telephone number, and social security number when you create an account. </li>
                                    <li>We will collect the financial and transaction information necessary to provide you with the Services, including account numbers, payment card expiration date, payment card identification, verification numbers, and transaction and payment history. </li>
                                    <li>If you provide feedback or contact us via email, we will collect your name and email address, as well as any other content included in the email, in order to send you a reply.</li>
                                    <li>We also collect other types of personal information that you provide voluntarily, such as any information requested by us if you contact us via email regarding support for the Services.</li>

                                    <p><strong>(b)</strong> Personal Information Collected from Third Parties—We may collect certain information from identity verification services and consumer reporting agencies, including credit bureaus, in order to provide some of our Services.</p>
                                    <p><strong>(c)</strong> Personal Information Collected Via Technology—We and our service providers may automatically log information about you, your computer or mobile device, and your interaction over time with our Services, our communications, and other online services, such as: </p>
                                    <li>Device data, such as your computer or mobile device’s operating system type and version, manufacturer and model, browser type, screen resolution, RAM and disk size, CPU usage, device type (example: phone, tablet), IP address, unique identifiers, language settings, mobile device carrier, radio/network information (example: Wi-Fi, LTE, 3G), and general location information such as city, state, or geographic area. </li>
                                    <li>Online activity data, such as pages or screens you viewed, how long you spent on a page or screen, the website you visited before browsing to the Service, navigation paths between pages or screens, information about your activity on a page or screen, access times, and duration of access. </li>
                                    <li>Cookies, which are text files that websites store on a visitor’s device to uniquely identify the visitor’s browser or to store information or settings in the browser for the purpose of helping you navigate between pages efficiently, remembering your preferences, enabling functionality, and helping us understand user activity and patterns. </li>
                                    <li>Local storage technologies, like HTML5, that provide cookie-equivalent functionality but can store larger amounts of data, including on your device outside of your browser in connection with specific applications. </li>
                                    <li>Web beacons, also known as pixel tags or clear GIFs, which are used to demonstrate that a webpage or email was accessed or opened, or that certain content was viewed or clicked.</li>
                                    <li>Location Information. If you have enabled location services on your phone and agree to the collection of your location when prompted by the Services, we will collect your location information when you use the Services; for example, to provide our fraud detection services. If you do not want us to collect this information, you may decline the collection of your location when prompted or adjust the location services settings on your device.</li>
                                    <li>Your Contacts: you can invite others to join your Ohana group by providing us with their contact information, or by allowing us to access contacts from your mobile device or third party sites to select which individuals you want to invite. Contacts typically contain information on individuals (or organizations) including names, email addresses, phone numbers, URLs, social handles, online identifiers, and physical addresses. Your Contacts may also contain additional information on individuals such as organizational affiliations, job titles, birthdays, key dates, age, gender, general location, relationships, skills, interests, preferences, notes, photos, tags and other categorizations. If you allow us to access your contacts, we may use this information to enhance your experience in various ways, including, but not limited to, notifying you when a contact has joined the service. In addition, other users who have your contact information and have chosen to upload, sync, or import it from their device may be notified of when you join our service; they may be able to know the number of people on the service who have your number in their uploaded contacts, so that they can choose to invite people with many friends already on the service. Finally, may we use your list of contacts (if you choose to provide us with access to them) to recommend other users you might want to follow and to recommend your account and content to others.</li>
                                    <li>Communications: when you sign up for an account or use certain features, you are opting to receive messages from other users, and Ohana. you can manage some of your messaging preferences through app settings and your device settings. </li>
                                    <li>Ohana app requires microphone access permission to enable voice messaging functionality of the app. The microphone permission is optional and only requested when starting an audio recording. No connections or access will ever be made to user device without the user requesting it. It stores settings internally and pictures/videos captured by the user in device media store for the profile.</li>
                                    <li>The app does use third-party services that may collect information used to identify you. Link to the privacy policy of third-party service providers used by the app
                                    </li>
                                    <p>Link to the privacy policy of third-party service providers used by the app</p>
                                    <li>Google Play Services</li>
                                    <li>Google Analytics for Firebase</li>
                                    <li>Firebase Crashlytics</li>
                                    <li><strong>Log Data:</strong> We want to inform you that whenever you use our Service, in a case of an error in the app we collect data and information (through third-party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing our Service, the time and date of your use of the Service, and other statistics.</li>
                                    <li><strong>Cookies:</strong> Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory. This Service does not use these “cookies” explicitly. However, the app may use third-party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.</li>
                                    <h4 className="font-weight-bold text-black">HOW WE USE YOUR INFORMATION COLLECTED IN THE APP</h4>
                                    <p></p>
                                    <h4 className="font-weight-bold text-black"></h4>
                                    <p><strong>(a)</strong> General Use—In general, we use your personal information collected through your use of the Services to respond to your requests as submitted through the Services, to provide you the Services you request, and to help serve you better. We use your personal information, in connection with the App, in the following ways: </p>
                                    <li>Facilitate the creation of, and secure and maintain your account; </li>
                                    <li>Identify you as a legitimate user in our system; </li>
                                    <li>Provide improved administration of the Services; </li>
                                    <li>Provide the Services you request; </li>
                                    <li>Improve the quality of experience when you interact with the Services; </li>
                                    <li>Send you administrative email notifications, such as security or support and maintenance advisories; and </li>
                                    <li>Send surveys, offers, and other promotional materials related to the Services.</li>
                                    <p><strong>(b)</strong> Compliance and protection—We may use your personal information to: </p>
                                    <li>Comply with applicable laws, lawful requests and legal process, such as to respond to subpoenas or requests from government authorities; </li>
                                    <li>Protect our, your or others’ rights, privacy, safety or property (including by making and defending legal claims); </li>
                                    <li>Audit our internal processes for compliance with legal and contractual requirements and internal policies; </li>
                                    <li>Enforce the terms and conditions that govern the Service</li>
                                    <li>Prevent, identify, investigate and deter fraudulent, harmful, unauthorized, unethical, or illegal activity, including cyberattacks and identity theft.</li>
                                    <p><strong>(c)</strong> Creation of Non-Identifiable Data—The App may create de-identified information records from personal information by excluding certain information (such as your name) that makes the information personally identifiable to you. We may use this information in a form that does not personally identify you to analyze request patterns and usage patterns to enhance our products and services. We reserve the right to use and disclose non-identifiable information to third parties in our discretion.</p>
                                    <h4 className="font-weight-bold text-black">DISCLOSURE OF YOUR PERSONAL INFORMATION</h4>
                                    <p>We disclose your personal information collected through your use of the Services as described below.</p>
                                    <p><strong>(a)</strong> In Accordance with Our Other Privacy Notices—Other than as described in this Privacy Policy in connection with the App, this Privacy Policy does not apply to the processing of your information by us or third parties with whom we share information.</p>
                                    <p><strong>(b)</strong> Third Party Service Providers—We may share your personal information with third party or affiliated service providers that perform services for or on behalf of us in providing the App, for the purposes described in this Privacy Policy, including: to provide you with the Services; to conduct quality assurance testing; to facilitate the creation of accounts; to optimize the performance of the Services; to provide technical support; and/or to provide other services to the App.</p>
                                    <p><strong>(c)</strong> Authorities and Others—Regardless of any choices you make regarding your personal information, The App may disclose your personal information to law enforcement, government authorities, and private parties, for the compliance and protection services described above.</p>
                                    <h4 className="font-weight-bold text-black">LINKS TO OTHER SITES</h4>
                                    <p>The App may contain links to third party websites. When you click on a link to any other website or location, you will leave the App and go to another site, and another entity may collect personal and/or anonymous information from you. The App’s provision of a link to any other website or location is for your convenience and does not signify our endorsement of such other website or location or its contents. We have no control over, do not review, and cannot be responsible for, these outside websites or their content. Please be aware that the terms of this Privacy Policy do not apply to these outside websites. We encourage you to read the privacy policy of every website you visit.</p>
                                    <h4 className="font-weight-bold text-black">YOUR CHOICES REGARDING YOUR INFORMATION</h4>
                                    <p><strong>(a)</strong> How We Respond to Do Not Track Signals—Some web browsers transmit “do not track” signals to the websites and other online services with which your web browser communicates. There is currently no standard that governs what, if anything, websites should do when they receive these signals. We currently do not take action in response to these signals. If and when a standard is established, we may revise its policy on responding to these signals.</p>
                                    <p><strong>(b)</strong> Access, Update, or Correct Your Information—You can access, update, or correct your information by changing preferences in your account. For additional requests, please contact us.</p>
                                    <p><strong>(c)</strong> Opting Out of Email or SMS Communications—If you have signed-up to receive our email marketing communications, you can unsubscribe any time by clicking the "unsubscribe" link included at the bottom of the email or other electronic communication. Alternatively, you can opt out of receiving marketing communications by contacting us at the contact information under "Contact Us" below. If you provide your phone number through the Services, we may send you notifications by SMS, such as provide a fraud alert. You may opt out of SMS communications by unlinking your mobile phone number through the Services.</p>
                                    <p><strong>(d)</strong> Opting Out of Location Tracking—If you initially consented to the collection of geo-location information through the Services, you can subsequently stop the collection of this information at any time by changing the preferences on your mobile device. Please note, if you withdraw consent to our collection of location information, you may no longer be able to use some features of the App.</p>
                                    <h4 className="font-weight-bold text-black">SAFEGUARDS AND RETENTION</h4>
                                    <p>We implement reasonable administrative, technical, and physical measures in an effort to safeguard the information in our custody and control against theft, loss and unauthorized access, use, modification, and disclosure. Nevertheless, transmission via the internet is not completely secure and we cannot guarantee the security of your information.</p>
                                    <h4 className="font-weight-bold text-black">A NOTE ABOUT CHILDREN</h4>
                                    <p>We do not use the Services to knowingly solicit personal information from or market to children under the age of thirteen (13) without parental consent. We request that such individuals do not provide personal information through the Services. If a parent or guardian becomes aware that his or her child has provided us with information without their consent, he or she should promptly contact us at support@ohana.africa or at +228 92105147 and we will delete such information from our files.</p>
                                    <h4 className="font-weight-bold text-black">PRIVACY POLICY UPDATES</h4>
                                    <p>This Privacy Policy is subject to occasional revision. We will notify you of any material changes in its collection, use, or disclosure of your personal information by posting a notice on the Services. Any material changes to this Privacy Policy will be effective thirty (30) calendar days following notice of the changes on the Services. These changes will be effective immediately for new users of the Services. If you object to any such changes, you must notify us prior to the effective date of such changes that you wish to deactivate your account. Continued use of the Services following notice of any such changes shall indicate your acknowledgement of such changes.</p>
                                    <h4 className="font-weight-bold text-black">CONTACT US</h4>
                                    <p>If you have any questions or complaints about this Privacy Policy or The App’s data collection or processing practices, or if you want to report any security violations to The App, please contact The App by email at: support@ohana.africa; or by mail at: PO BOX 76, Atakpamé, Togo</p>
                                    <h4 className="font-weight-bold text-black">COMMUNICATION</h4>
                                    <p>We may provide you electronically with information about your transactions, our products, and agreements between us. You hereby agree to receive such communication electronically. We may also contact you via SMS or a phone call on the telephone numbers you provided to us during registration, however not for the purpose of marketing unless we receive your prior written consent.
                                        You can withdraw your consent to receive marketing communication by contacting us on the details below. If you opt-out from receiving the marketing communication, this will not affect communication relevant to your use of the Service.
                                        Haagbo, SarlU<br></br>
                                        BP 76 Atakpamé
                                        Togo<br></br>
                                        E-mail: support@ohana.africa
                                    </p>
                                </div>
                                <div hidden={isFrench == false}>
                                    <h2 className="font-weight-bold text-black">POLITIQUE DE CONFIDENTIALITÉ</h2>
                                    <h4 className="font-weight-bold text-black">GÉNÉRALITÉS</h4>
                                    <p>
                                        Ohana Africa ("Ohana Africa", "nous", "notre" ou "nos") reconnaît l'importance de protéger les détails et les informations personnelles, et fournit donc cette politique de confidentialité en ce qui concerne l'accès et l'utilisation de divers produits et services de Ohana Africa par le biais de tout type de dispositifs et de médias, y compris les applications basées sur le web, les applications mobiles, les dispositifs, les URL/liens, les notifications, le chatbot et d'autres formes de médias numériques ou non numériques, ("Plateformes") telles que détenues et exploitées par nous et/ou nos sociétés affiliées et les services fournis sur celles-ci par nous et/ou nos sociétés affiliées ("Services"). Le terme Plateformes inclura également toutes les pages qui sont des sous-domaines ou sont associées à ou dans chaque Plateforme et tous les dispositifs, applications, caractéristiques, technologies, fonctionnalités et autres services que Ohana Africa exploite ou offre par le biais de ces Plateformes. Aux fins de la présente Politique de confidentialité, l'utilisateur des Services peut être un client, un partenaire de distribution, un vendeur ou toute autre personne utilisant les Services ou accédant aux Plateformes (" utilisateur ", " vous " ou " votre "). La présente politique de confidentialité vous aidera à comprendre nos politiques et procédures concernant la collecte, le traitement et l'utilisation de vos informations.
                                        Nous nous engageons à respecter votre vie privée en ligne et reconnaissons votre besoin de protection et de gestion appropriées de toute information que vous partagez avec nous sur la plate-forme. La présente politique de confidentialité ("politique") est élaborée conformément à la législation applicable.
                                        En utilisant nos Services par l'intermédiaire des Plateformes, vous signifiez votre assentiment à la présente Politique et consentez au traitement de vos informations personnelles et/ou de vos données personnelles sensibles ou de toute autre transaction générée par votre utilisation des Plateformes ("Informations"). Si, à tout moment, une personne fournit des Informations sur une personne autre que lui-même, la personne garantit qu'elle a le consentement de cette personne pour fournir ces informations aux fins spécifiées. Les Services ne sont pas accessibles aux personnes âgées de moins de 18 ans.
                                        Si vous n'êtes pas d'accord avec la présente Politique, veillez à ne pas utiliser, de quelque manière que ce soit, nos Services ou télécharger, installer et/ou utiliser l'application mobile.
                                    </p>
                                    <h4 className="font-weight-bold text-black">PORTÉE</h4>
                                    <p>En accédant ou en utilisant la Plateforme et/ou en profitant des services fournis par l'intermédiaire de la Plateforme ou en nous fournissant autrement vos informations, vous vous engagez à avoir la capacité de conclure un contrat juridiquement contraignant vide cette Politique, qui constitue un document juridiquement contraignant entre vous et Ohana Africa en vertu de la loi applicable. Ohana Africa collecte et traite vos données d'utilisation, vos données personnelles et vos données de tiers avec soin, uniquement aux fins décrites dans la présente Politique et seulement dans la mesure nécessaire telle que définie ici et dans le cadre de toutes les réglementations légales applicables. Cette Politique vise à assurer que toute information personnelle ou information de tiers traitée par Ohana Africa est gérée de manière éthique, conforme et adhère aux meilleures pratiques du secteur.

                                        Cette politique décrit les types d'informations que Ohana Africa collecte, pourquoi et comment Ohana Africa utilise ces informations, avec qui Ohana Africa les partage, et les choix que vous pouvez faire concernant l'utilisation de ces informations par Ohana Africa. Nous décrivons également les mesures prises par nous pour protéger la sécurité des informations et comment vous pouvez contacter Ohana Africa au sujet de ses pratiques de confidentialité.

                                        La présente Politique décrit les politiques et pratiques actuelles de Ohana Africa en matière de protection des données, qui peuvent être modifiées ou mises à jour de temps à autre. Toute modification de la présente Politique entrera en vigueur dès la publication de la Politique révisée sur la Plateforme. Il est recommandé de vérifier régulièrement cette Politique pour vous informer de toute mise à jour. Votre utilisation continue de la plate-forme ou la fourniture de données ou d'informations par la suite impliquera votre acceptation inconditionnelle de ces mises à jour de la présente politique.

                                    </p>
                                    <h4 className="font-weight-bold text-black">COLLECTE D'INFORMATIONS</h4>
                                    <p>Nous avons l'intention de fournir des services et des fonctionnalités qui répondent à vos besoins. Pour ce faire, lorsque vous utilisez nos plates-formes, nous pouvons obtenir les informations suivantes sur vous et votre appareil à partir duquel vous utilisez les services</p>
                                    <h4 className="font-weight-bold text-black">LES TYPES D'INFORMATIONS QUE NOUS RECUEILLONS DANS L'APPLICATION</h4>

                                    <p>Par le biais de votre utilisation des Services, nous pouvons recueillir des informations personnelles de votre part de la manière suivante :</p>
                                    <strong>(a)</strong> Informations personnelles que vous nous fournissez
                                    <li>Nous pouvons recueillir des informations personnelles auprès de vous, telles que votre nom et prénom, votre adresse, votre courriel, votre numéro de téléphone et votre numéro de sécurité sociale lorsque vous créez un compte.   </li>
                                    <li>Nous recueillons les informations financières et de transaction nécessaires pour vous fournir les services, notamment les numéros de compte, la date d'expiration de la carte de paiement, l'identification de la carte de paiement, les numéros de vérification et l'historique des transactions et des paiements.  </li>
                                    <li>Si vous nous faites part de vos commentaires ou nous contactez par courrier électronique, nous recueillerons votre nom et votre adresse électronique, ainsi que tout autre contenu inclus dans le courrier électronique, afin de vous envoyer une réponse.</li>
                                    <li>Nous recueillons également d'autres types d'informations personnelles que vous fournissez volontairement, telles que les informations que nous vous demandons si vous nous contactez par courrier électronique au sujet de l'assistance aux Services.</li>
                                    <p><strong>(b)</strong> Informations personnelles recueillies auprès de tiers - Nous pouvons recueillir certaines informations auprès de services de vérification d'identité et d'agences d'évaluation du crédit, y compris des agences d'évaluation du crédit, afin de fournir certains de nos services.</p>
                                    <p><strong>(c)</strong> Informations personnelles collectées via la technologie-Nous et nos prestataires de services pouvons enregistrer automatiquement des informations vous concernant, votre ordinateur ou votre appareil mobile, et votre interaction au fil du temps avec nos Services, nos communications et d'autres services en ligne, telles que :   </p>
                                    <li>Données relatives à l'appareil, telles que le type et la version du système d'exploitation de votre ordinateur ou de votre appareil mobile, le fabricant et le modèle, le type de navigateur, la résolution de l'écran, la taille de la RAM et du disque, l'utilisation de l'unité centrale, le type d'appareil (exemple : téléphone, tablette), l'adresse IP, les identifiants uniques, les paramètres linguistiques, l'opérateur de l'appareil mobile, les informations sur la radio/le réseau (exemple : Wi-Fi, LTE, 3G) et les informations générales de localisation telles que la ville, l'État ou la zone géographique.   </li>
                                    <li>Les données d'activité en ligne, telles que les pages ou les écrans que vous avez consultés, le temps que vous avez passé sur une page ou un écran, le site Web que vous avez visité avant de naviguer sur le Service, les chemins de navigation entre les pages ou les écrans, les informations sur votre activité sur une page ou un écran, les heures d'accès et la durée de l'accès.   </li>
                                    <li>Les cookies, qui sont des fichiers texte que les sites web stockent sur l'appareil d'un visiteur pour identifier de manière unique le navigateur du visiteur ou pour stocker des informations ou des paramètres dans le navigateur dans le but de vous aider à naviguer efficacement entre les pages, de se souvenir de vos préférences, d'activer des fonctionnalités et de nous aider à comprendre l'activité et les modèles des utilisateurs. </li>
                                    <li>Les technologies de stockage local, comme le HTML5, qui fournissent une fonctionnalité équivalente à celle des cookies mais peuvent stocker des quantités plus importantes de données, y compris sur votre appareil en dehors de votre navigateur en relation avec des applications spécifiques.   </li>
                                    <li>Les balises Web, également connues sous le nom de pixels ou de GIF transparents, qui sont utilisées pour démontrer qu'une page Web ou un courriel a été consulté ou ouvert, ou qu'un certain contenu a été vu ou cliqué.  </li>
                                    <li>Informations de localisation. Si vous avez activé les services de localisation sur votre téléphone et que vous acceptez la collecte de votre localisation lorsque les Services vous y invitent, nous collecterons vos informations de localisation lorsque vous utiliserez les Services, par exemple, pour fournir nos services de détection des fraudes. Si vous ne souhaitez pas que nous recueillions ces informations, vous pouvez refuser la collecte de votre localisation lorsque vous y êtes invité ou ajuster les paramètres des services de localisation sur votre appareil.</li>
                                    <li>Vos contacts : vous pouvez inviter d'autres personnes à rejoindre votre groupe Ohana en nous fournissant leurs coordonnées, ou en nous permettant d'accéder aux contacts de votre appareil mobile ou de sites tiers pour sélectionner les personnes que vous souhaitez inviter. Les contacts contiennent généralement des informations sur des personnes (ou des organisations), notamment des noms, des adresses électroniques, des numéros de téléphone, des URL, des poignées sociales, des identifiants en ligne et des adresses physiques. Vos contacts peuvent également contenir des informations supplémentaires sur des personnes, telles que des affiliations organisationnelles, des titres professionnels, des anniversaires, des dates clés, l'âge, le sexe, l'emplacement général, les relations, les compétences, les intérêts, les préférences, les notes, les photos, les balises et d'autres catégorisations. Si vous nous autorisez à accéder à vos contacts, nous pouvons utiliser ces informations pour améliorer votre expérience de diverses manières, y compris, mais sans s'y limiter, en vous informant lorsqu'un contact a rejoint le service. En outre, d'autres utilisateurs qui disposent de vos coordonnées et qui ont choisi de les télécharger, de les synchroniser ou de les importer à partir de leur appareil peuvent être avertis lorsque vous rejoignez notre service ; ils peuvent être en mesure de connaître le nombre de personnes sur le service qui ont votre numéro dans leurs contacts téléchargés, de sorte qu'ils peuvent choisir d'inviter des personnes ayant déjà beaucoup d'amis sur le service. Enfin, nous pouvons utiliser votre liste de contacts (si vous choisissez de nous en donner l'accès) pour vous recommander d'autres utilisateurs que vous pourriez vouloir suivre et pour recommander votre compte et votre contenu à d'autres personnes. </li>
                                    <li>Communications : lorsque vous vous inscrivez à un compte ou que vous utilisez certaines fonctionnalités, vous choisissez de recevoir des messages d'autres utilisateurs et d'Ohana. Vous pouvez gérer certaines de vos préférences de messagerie par le biais des paramètres de l'application et de votre appareil. </li>
                                    <li>L'application Ohana nécessite une autorisation d'accès au microphone pour activer la fonctionnalité de messagerie vocale de l'application. L'autorisation d'accès au microphone est facultative et n'est demandée que lors du lancement d'un enregistrement audio. Aucune connexion ou accès ne sera jamais effectué sur l'appareil de l'utilisateur sans que celui-ci ne le demande. L'application stocke les paramètres en interne et les photos/vidéos capturées par l'utilisateur dans le magasin multimédia de l'appareil pour le profil.
                                    </li>
                                    <li>L'application utilise des services tiers qui peuvent recueillir des informations permettant de vous identifier.</li>
                                    <p>Lien vers la politique de confidentialité des fournisseurs de services tiers utilisés par l'application.</p>
                                    <li>Google Play Services</li>
                                    <li>Google Analytics for Firebase</li>
                                    <li>Firebase Crashlytics</li>
                                    <li><strong>Données du journal :</strong>  Nous souhaitons vous informer qu'à chaque fois que vous utilisez notre Service, dans le cas d'une erreur dans l'application, nous collectons des données et des informations (par le biais de produits tiers) sur votre téléphone appelées Données de journal. Ces données peuvent inclure des informations telles que l'adresse du protocole Internet ("IP") de votre appareil, le nom de l'appareil, la version du système d'exploitation, la configuration de l'application lors de l'utilisation de notre service, l'heure et la date de votre utilisation du service et d'autres statistiques.</li>
                                    <li><strong>Cookies:</strong> Les cookies sont des fichiers contenant une petite quantité de données qui sont généralement utilisés comme identifiants uniques anonymes. Ils sont envoyés à votre navigateur à partir des sites web que vous visitez et sont stockés dans la mémoire interne de votre appareil. Ce service n'utilise pas explicitement ces "cookies". Cependant, l'application peut utiliser du code et des bibliothèques de tiers qui utilisent des "cookies" pour collecter des informations et améliorer leurs services. Vous avez la possibilité d'accepter ou de refuser ces cookies et de savoir quand un cookie est envoyé à votre appareil. Si vous choisissez de refuser nos cookies, il se peut que vous ne puissiez pas utiliser certaines parties de ce service.</li>
                                    <h4 className="font-weight-bold text-black">COMMENT NOUS UTILISONS VOS INFORMATIONS RECUEILLIES DANS L'APPLICATION</h4>
                                    <p><strong>(a)</strong> Utilisation générale - En général, nous utilisons vos informations personnelles collectées par le biais de votre utilisation des Services pour répondre à vos demandes telles que soumises par le biais des Services, pour vous fournir les Services que vous demandez et pour mieux vous servir. Nous utilisons vos informations personnelles, en relation avec l'application, de la manière suivante :  </p>
                                    <li>Faciliter la création de votre compte, le sécuriser et le maintenir ;  </li>
                                    <li>Vous identifier en tant qu'utilisateur légitime dans notre système ;  </li>
                                    <li>Fournir une administration améliorée des Services ;  </li>
                                    <li>Fournir les Services que vous demandez ;  </li>
                                    <li>Améliorer la qualité de l'expérience lorsque vous interagissez avec les Services ;  </li>
                                    <li>Vous envoyer des notifications administratives par e-mail, telles que des avis de sécurité ou de support et de maintenance ; et  </li>
                                    <li>Envoyer des enquêtes, des offres et d'autres matériels promotionnels liés aux Services.</li>
                                    <p><strong>(b)</strong> Conformité et protection-Nous pouvons utiliser vos informations personnelles pour:  </p>
                                    <li>- nous conformer aux lois applicables, aux demandes légitimes et aux procédures légales, par exemple pour répondre aux citations à comparaître ou aux demandes des autorités gouvernementales ;</li>
                                    <li>protéger nos droits, votre vie privée, votre sécurité ou la propriété d'autrui (y compris en faisant et en défendant des réclamations légales) ;  </li>
                                    <li>vérifier nos processus internes pour assurer la conformité aux exigences légales et contractuelles et aux politiques internes ;  </li>
                                    <li>appliquer les conditions générales qui régissent le Service ; et  </li>
                                    <li>prévenir, identifier, enquêter et décourager les activités frauduleuses, nuisibles, non autorisées, non éthiques ou illégales, y compris les cyberattaques et le vol d'identité.</li>

                                    <p><strong>(c)</strong> Création de données non identifiables - L'application peut créer des enregistrements d'informations non identifiées à partir d'informations personnelles en excluant certaines informations (telles que votre nom) qui rendent les informations personnellement identifiables pour vous. Nous pouvons utiliser ces informations sous une forme qui ne vous identifie pas personnellement pour analyser les modèles de demande et d'utilisation afin d'améliorer nos produits et services. Nous nous réservons le droit d'utiliser et de divulguer des informations non identifiables à des tiers, à notre discrétion.</p>
                                    <h4 className="font-weight-bold text-black">DIVULGATION DE VOS INFORMATIONS PERSONNELLES</h4>
                                    <p>Nous divulguons vos informations personnelles recueillies lors de votre utilisation des services comme décrit ci-dessous.</p>
                                    <p><strong>(a)</strong> Conformément à nos autres avis de confidentialité - À l'exception de ce qui est décrit dans la présente politique de confidentialité en relation avec l'App, la présente politique de confidentialité ne s'applique pas au traitement de vos informations par nous ou par des tiers avec lesquels nous partageons des informations.</p>
                                    <p><strong>(b)</strong> Prestataires de services tiers - Nous pouvons partager vos informations personnelles avec des prestataires de services tiers ou affiliés qui effectuent des services pour nous ou en notre nom dans le cadre de la fourniture de l'App, aux fins décrites dans la présente Politique de confidentialité, notamment : pour vous fournir les Services ; pour effectuer des tests d'assurance qualité ; pour faciliter la création de comptes ; pour optimiser les performances des Services ; pour fournir une assistance technique ; et/ou pour fournir d'autres services à l'App.</p>
                                    <p><strong>(c)</strong> Autorités et autres - Indépendamment des choix que vous faites concernant vos informations personnelles, The App peut divulguer vos informations personnelles aux autorités policières, gouvernementales et privées, pour les services de conformité et de protection décrits ci-dessus.</p>
                                    <h4 className="font-weight-bold text-black">LIENS VERS D'AUTRES SITES</h4>
                                    <p>L'application peut contenir des liens vers des sites web de tiers. Lorsque vous cliquez sur un lien vers un autre site web ou emplacement, vous quittez l'application et accédez à un autre site, et une autre entité peut recueillir des informations personnelles et/ou anonymes auprès de vous. La fourniture par l'application d'un lien vers tout autre site web ou emplacement est destinée à votre confort et ne signifie pas que nous approuvons cet autre site web ou emplacement ou son contenu. Nous n'avons aucun contrôle sur ces sites extérieurs ou leur contenu, ne les examinons pas et ne pouvons en être tenus responsables. Veuillez noter que les conditions de la présente politique de confidentialité ne s'appliquent pas à ces sites Web externes. Nous vous encourageons à lire la politique de confidentialité de chaque site Web que vous visitez.</p>
                                    <h4 className="font-weight-bold text-black">VOS CHOIX CONCERNANT VOS INFORMATIONS</h4>
                                    <p>Vous avez plusieurs choix concernant l'utilisation des informations sur les services.</p>
                                    <p><strong>(a)</strong> Comment nous répondons aux signaux "Do Not Track" - Certains navigateurs Web transmettent des signaux "Do Not Track" aux sites Web et autres services en ligne avec lesquels votre navigateur Web communique. Il n'existe actuellement aucune norme régissant ce que les sites Web doivent faire, le cas échéant, lorsqu'ils reçoivent ces signaux. Nous ne prenons actuellement aucune mesure en réponse à ces signaux. Si et quand une norme sera établie, nous pourrons réviser notre politique de réponse à ces signaux.</p>
                                    <p><strong>(b)</strong> Accès, mise à jour ou correction de vos informations - Vous pouvez accéder, mettre à jour ou corriger vos informations en modifiant les préférences de votre compte. Pour toute demande supplémentaire, veuillez nous contacter.</p>
                                    <p><strong>(c)</strong> Refus des communications par e-mail ou SMS - Si vous vous êtes inscrit pour recevoir nos communications marketing par e-mail, vous pouvez vous désinscrire à tout moment en cliquant sur le lien " se désinscrire " figurant au bas de l'e-mail ou de toute autre communication électronique. Vous pouvez également choisir de ne plus recevoir de communications commerciales en nous contactant aux coordonnées indiquées dans la section "Nous contacter" ci-dessous. Si vous fournissez votre numéro de téléphone par le biais des Services, nous pouvons vous envoyer des notifications par SMS, par exemple pour vous avertir d'une fraude. Vous pouvez choisir de ne pas recevoir de communications par SMS en dissociant votre numéro de téléphone portable par le biais des Services.</p>
                                    <p><strong>(d)</strong> Retrait du suivi de la localisation-Si vous avez initialement consenti à la collecte d'informations de géolocalisation par le biais des Services, vous pouvez par la suite arrêter la collecte de ces informations à tout moment en modifiant les préférences de votre appareil mobile. Veuillez noter que si vous retirez votre consentement à notre collecte d'informations de localisation, il se peut que vous ne puissiez plus utiliser certaines fonctionnalités de l'App.</p>
                                    <h4 className="font-weight-bold text-black">SAUVEGARDES ET CONSERVATION</h4>
                                    <p>Nous mettons en œuvre des mesures administratives, techniques et physiques raisonnables afin de protéger les informations dont nous avons la garde et le contrôle contre le vol, la perte et l'accès, l'utilisation, la modification et la divulgation non autorisés. Néanmoins, la transmission par Internet n'est pas totalement sûre et nous ne pouvons pas garantir la sécurité de vos informations.</p>
                                    <h4 className="font-weight-bold text-black">NOTE CONCERNANT LES ENFANTS</h4>
                                    <p>Nous n'utilisons pas les Services pour solliciter sciemment des informations personnelles auprès d'enfants de moins de treize (13) ans ou pour les commercialiser sans le consentement de leurs parents. Nous demandons à ces personnes de ne pas fournir d'informations personnelles par le biais des Services. Si un parent ou un tuteur apprend que son enfant nous a fourni des informations sans son consentement, il doit nous contacter rapidement à l'adresse suivante support@ohana.africa ou au +228 92105147 et nous supprimerons ces informations de nos fichiers.</p>
                                    <h4 className="font-weight-bold text-black">MISES À JOUR DE LA POLITIQUE DE CONFIDENTIALITÉ</h4>
                                    <p>La présente politique de confidentialité est sujette à des révisions occasionnelles. Nous vous informerons de tout changement important dans la collecte, l'utilisation ou la divulgation de vos informations personnelles en publiant un avis sur les Services. Toute modification importante de la présente politique de confidentialité entrera en vigueur trente (30) jours calendaires après la publication des modifications sur les services. Ces modifications prendront effet immédiatement pour les nouveaux utilisateurs des services. Si vous vous opposez à de tels changements, vous devez nous notifier avant la date d'entrée en vigueur de ces changements que vous souhaitez désactiver votre compte. La poursuite de l'utilisation des services après la notification de ces changements indique que vous reconnaissez ces changements.</p>
                                    <h4 className="font-weight-bold text-black">CONTACTEZ-NOUS</h4>
                                    <p>Si vous avez des questions ou des plaintes concernant la présente politique de confidentialité ou les pratiques de collecte ou de traitement des données de The App, ou si vous voulez signaler des violations de sécurité à The App, veuillez contacter The App par courriel à l'adresse suivante : support@ohana.africa ; ou par courrier à l'adresse suivante : PO BOX 76, Atakpamé, Togo</p>
                                    <h4 className="font-weight-bold text-black">COMMUNICATION</h4>
                                    <p>Nous pouvons vous fournir par voie électronique des informations sur vos transactions, nos produits et les accords entre nous. Vous acceptez par la présente de recevoir ces communications par voie électronique. Nous pouvons également vous contacter par SMS ou par appel téléphonique aux numéros de téléphone que vous nous avez fournis lors de votre inscription, mais pas à des fins de marketing, sauf si nous recevons votre consentement écrit préalable.
                                        Vous pouvez retirer votre consentement à recevoir des communications marketing en nous contactant aux coordonnées ci-dessous. Si vous refusez de recevoir la communication marketing, cela n'affectera pas la communication relative à votre utilisation du service.
                                        Haagbo, SarlU
                                        <br></br>
                                        BP 76 Atakpamé
                                        Togo<br></br>
                                        Courriel: support@ohana.africa
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}
export default PrivacyPolicy;